# Generated by Django 4.1 on 2022-10-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="USER",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(default=0, null=True)),
                ("job", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("add", models.CharField(max_length=255)),
            ],
        ),
    ]
