# Generated by Django 4.1 on 2022-10-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_email_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                ("log_idx", models.AutoField(primary_key=True, serialize=False)),
                ("log_id", models.CharField(max_length=10)),
                ("log_password", models.CharField(max_length=50)),
            ],
        ),
    ]
